#!/usr/bin/env python3
"""Generate crypto interop fixtures for the Flutter client's tests.

Writes a JSON file the Dart tests read, so the Dart implementation is asserted
against values produced by the same library the server uses (pycryptodome)
rather than against the Dart implementation's own output.

The file contains three kinds of vector:

* **Deterministic digests and HMACs** — Dart must reproduce these exactly.
* **Python-encrypted AES-GCM payloads** — Dart must decrypt these, proving it
  reads the server's `iv` / `ct||tag` / base64 layout correctly.
* **An RSA keypair** — the public half lets Dart wrap a key, and the private half
  lets the round-trip test confirm the server could unwrap it. A throwaway
  keypair is generated per run; it is test-only and never used in production.

Usage:
    .venv/bin/python scripts/gen_crypto_fixtures.py \
        ../duiliao_app/assets/fixtures/crypto_vectors.json
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import json
import secrets
import sys
from pathlib import Path

from Crypto.Cipher import AES, PKCS1_OAEP
from Crypto.Hash import SHA256
from Crypto.PublicKey import RSA

IV_LEN = 12
TAG_LEN = 16
SIGNING_SECRET = "fixture-signing-secret"


def b64e(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def aes_encrypt(key: bytes, plaintext: bytes, iv: bytes) -> dict[str, str]:
    cipher = AES.new(key, AES.MODE_GCM, nonce=iv, mac_len=TAG_LEN)
    ct, tag = cipher.encrypt_and_digest(plaintext)
    return {"iv": b64e(iv), "ciphertext": b64e(ct + tag)}


def build() -> dict:
    # --- digests ---------------------------------------------------------- #
    sha_cases = ["", "abc", "duiliao", "澳门六合彩 2026248", "a" * 1000]

    # --- HMAC ------------------------------------------------------------- #
    hmac_cases = [
        {"secret": "secret", "message": "message"},
        {"secret": SIGNING_SECRET, "message": "sid\n1700000000\ndeadbeef\n" + hashlib.sha256(b"").hexdigest()},
        {"secret": "unicode-秘密", "message": "特码\n单双\n大小"},
    ]

    # --- canonical signing strings ---------------------------------------- #
    signing_cases = []
    for session_id, timestamp, nonce, body in [
        ("sess-abc", "1700000000", "0123456789abcdef0123456789abcdef", b""),
        ("sess-xyz", "1767225600", "ffffffffffffffffffffffffffffffff", b'{"iv":"AAA","ciphertext":"BBB"}'),
    ]:
        canonical = "\n".join(
            [session_id, timestamp, nonce, hashlib.sha256(body or b"").hexdigest()]
        )
        signing_cases.append(
            {
                "session_id": session_id,
                "timestamp": timestamp,
                "nonce": nonce,
                "body_utf8": body.decode("utf-8"),
                "canonical": canonical,
                "signature": hmac.new(
                    SIGNING_SECRET.encode("utf-8"), canonical.encode("utf-8"), hashlib.sha256
                ).hexdigest(),
            }
        )

    # --- AES-GCM payloads Dart must decrypt ------------------------------- #
    aes_key = secrets.token_bytes(32)
    aes_cases = []
    for plaintext in [
        b"",
        b"hello duiliao",
        json.dumps({"ok": True, "period": "2026248", "tema": "28"}, ensure_ascii=False).encode(),
        "澳门 平特肖 猪猪猪".encode(),
        secrets.token_bytes(4096),
    ]:
        iv = secrets.token_bytes(IV_LEN)
        envelope = aes_encrypt(aes_key, plaintext, iv)
        aes_cases.append(
            {
                "plaintext_b64": b64e(plaintext),
                "iv": envelope["iv"],
                "ciphertext": envelope["ciphertext"],
                # Proves the tag is appended rather than carried separately.
                "plaintext_len": len(plaintext),
                "blob_len": len(base64.b64decode(envelope["ciphertext"])),
            }
        )

    # --- RSA keypair ------------------------------------------------------ #
    rsa_key = RSA.generate(2048)
    sample_aes_key = secrets.token_bytes(32)
    wrapped = PKCS1_OAEP.new(rsa_key, hashAlgo=SHA256).encrypt(sample_aes_key)

    return {
        "_comment": (
            "Generated by backend/scripts/gen_crypto_fixtures.py. Test-only RSA "
            "keypair, regenerated on every run; never used in production."
        ),
        "signing_secret": SIGNING_SECRET,
        "iv_length": IV_LEN,
        "tag_length": TAG_LEN,
        "sha256": [
            {"input": case, "hex": hashlib.sha256(case.encode("utf-8")).hexdigest()}
            for case in sha_cases
        ],
        "hmac_sha256": [
            {
                **case,
                "hex": hmac.new(
                    case["secret"].encode("utf-8"),
                    case["message"].encode("utf-8"),
                    hashlib.sha256,
                ).hexdigest(),
            }
            for case in hmac_cases
        ],
        "signing": signing_cases,
        "aes_gcm": {"key_b64": b64e(aes_key), "cases": aes_cases},
        "rsa": {
            "public_key_spki_b64": b64e(rsa_key.publickey().export_key(format="DER")),
            "private_key_pem": rsa_key.export_key().decode("ascii"),
            # A Python-produced wrap Dart does not need to reproduce (OAEP is
            # randomised) but which documents the expected size.
            "sample_wrapped_key_b64": b64e(wrapped),
            "sample_aes_key_b64": b64e(sample_aes_key),
            "wrapped_byte_length": len(wrapped),
        },
    }


def main() -> int:
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("crypto_vectors.json")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(build(), ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
