/// Client half of the Duiliao encrypted transport.
///
/// This is a 1:1 port of the primitives the backend expects. The authoritative
/// references are `backend/app/core/crypto.py`, `backend/app/core/security.py`
/// and the executable reference client at `backend/tests/crypto_client.py`;
/// every constant below is pinned by a test in `test/crypto_interop_test.dart`
/// against fixtures generated by the Python side.
///
/// ## Why pointycastle rather than package:webcrypto
///
/// `webcrypto` wraps BoringSSL and needs native build hooks (`hooks`,
/// `code_assets`, `native_toolchain_cmake`) to compile per platform. pointycastle
/// is pure Dart: it runs identically in `flutter test` on the host VM, on device,
/// and in a web build, with no platform toolchain and nothing to go wrong at
/// build time. The cost is roughly 40 lines of ASN.1 to unwrap an SPKI key, which
/// `asn1lib` handles, and slower RSA — irrelevant here because RSA is used once
/// per session to wrap a key, while every request body uses AES.
///
/// ## The three mistakes that break interoperability
///
/// 1. **RSA-OAEP must use SHA-256 for both the digest and MGF1, with no label.**
///    pointycastle's `OAEPEncoding(RSAEngine())` defaults MGF1 to SHA-1, which the
///    server silently fails to decrypt. Use [_oaepEncoder].
/// 2. **The GCM tag is appended to the ciphertext**, and pointycastle's
///    `GCMBlockCipher.process` already returns `ct || tag`. Do not append it again.
/// 3. **Base64 is the standard alphabet with padding**, not URL-safe. `+` and `/`
///    must survive.
library;

import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:asn1lib/asn1lib.dart';
import 'package:crypto/crypto.dart' as crypto;
import 'package:pointycastle/export.dart';

/// AES-GCM nonce length in bytes. The server generates 12 and rejects nothing
/// else in practice, because GCM is constructed with `nonce=iv`.
const int kIvLength = 12;

/// AES-GCM authentication tag length in bytes (128 bits).
const int kTagLength = 16;

/// Length of the AES session key in bytes (AES-256).
const int kAesKeyLength = 32;

/// SHA-256 of the empty string, which is the body hash used for requests with no
/// body (every GET and DELETE).
const String kEmptyBodySha256 =
    'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';

/// An AES-GCM encrypted payload, matching the JSON envelope on the wire.
class EncryptedEnvelope {
  const EncryptedEnvelope({required this.iv, required this.ciphertext});

  /// Standard base64 of the 12-byte nonce.
  final String iv;

  /// Standard base64 of `ciphertext || tag`.
  final String ciphertext;

  factory EncryptedEnvelope.fromJson(Map<String, dynamic> json) {
    final iv = json['iv'];
    final ciphertext = json['ciphertext'];
    if (iv is! String || ciphertext is! String) {
      throw const FormatException('envelope must have string iv and ciphertext');
    }
    return EncryptedEnvelope(iv: iv, ciphertext: ciphertext);
  }

  Map<String, String> toJson() => {'iv': iv, 'ciphertext': ciphertext};

  @override
  String toString() => 'EncryptedEnvelope(iv: $iv, ciphertext: <${ciphertext.length} chars>)';
}

/// Thrown when a payload fails to decrypt or authenticate.
class CryptoFailure implements Exception {
  const CryptoFailure(this.message);
  final String message;
  @override
  String toString() => 'CryptoFailure: $message';
}

/// Stateless crypto primitives. Instantiate with a custom [Random] only in tests.
class DuiliaoCrypto {
  DuiliaoCrypto({Random? random}) : _random = random ?? Random.secure();

  final Random _random;

  // ------------------------------------------------------------------ //
  // Randomness
  // ------------------------------------------------------------------ //
  Uint8List randomBytes(int length) {
    final out = Uint8List(length);
    for (var i = 0; i < length; i++) {
      out[i] = _random.nextInt(256);
    }
    return out;
  }

  /// A fresh 32-byte AES-256 session key.
  Uint8List generateAesKey() => randomBytes(kAesKeyLength);

  /// A request nonce: [byteLength] random bytes as lowercase hex.
  ///
  /// The default of 16 bytes yields the 32 hex characters the web client sends.
  /// An empty nonce is treated as a replay by the server, so this never returns
  /// an empty string.
  String randomNonceHex([int byteLength = 16]) => toHex(randomBytes(byteLength));

  // ------------------------------------------------------------------ //
  // Encoding
  // ------------------------------------------------------------------ //
  /// Lowercase hex, two digits per byte, no separators.
  static String toHex(List<int> bytes) {
    final sb = StringBuffer();
    for (final b in bytes) {
      sb.write((b & 0xff).toRadixString(16).padLeft(2, '0'));
    }
    return sb.toString();
  }

  /// Standard base64 **with** padding. Not URL-safe: the server decodes with
  /// `base64.b64decode`, which rejects the URL-safe alphabet.
  static String b64Encode(List<int> bytes) => base64.encode(bytes);

  static Uint8List b64Decode(String value) => base64.decode(value);

  /// Lowercase hex SHA-256 of [data].
  static String sha256Hex(List<int> data) =>
      toHex(crypto.sha256.convert(data).bytes);

  /// Lowercase hex HMAC-SHA-256. [secret] is hashed as its raw UTF-8 bytes.
  static String hmacSha256Hex(String secret, String message) {
    final mac = crypto.Hmac(crypto.sha256, utf8.encode(secret));
    return toHex(mac.convert(utf8.encode(message)).bytes);
  }

  // ------------------------------------------------------------------ //
  // Signing
  // ------------------------------------------------------------------ //
  /// The string the server signs, joined with LF and with no trailing newline.
  ///
  /// `bodyBytes` must be the **encrypted** request body exactly as sent — the
  /// UTF-8 bytes of the serialised `{"iv":...,"ciphertext":...}` JSON — not the
  /// plaintext. For a request with no body it is empty, hashing to
  /// [kEmptyBodySha256].
  static String canonicalString({
    required String sessionId,
    required String timestamp,
    required String nonce,
    required List<int> bodyBytes,
  }) =>
      [sessionId, timestamp, nonce, sha256Hex(bodyBytes)].join('\n');

  /// HMAC-SHA-256 of [canonicalString] as lowercase hex.
  static String signRequest({
    required String secret,
    required String sessionId,
    required String timestamp,
    required String nonce,
    required List<int> bodyBytes,
  }) =>
      hmacSha256Hex(
        secret,
        canonicalString(
          sessionId: sessionId,
          timestamp: timestamp,
          nonce: nonce,
          bodyBytes: bodyBytes,
        ),
      );

  // ------------------------------------------------------------------ //
  // RSA key wrapping
  // ------------------------------------------------------------------ //
  /// Parse a base64 DER SPKI (X.509 SubjectPublicKeyInfo) RSA public key.
  ///
  /// The handshake endpoint returns raw DER in base64, **not** PEM — there are no
  /// `-----BEGIN-----` armour lines to strip.
  static RSAPublicKey parseSpkiPublicKey(String spkiBase64) {
    final der = b64Decode(spkiBase64.trim());
    if (der.isEmpty || der.first != 0x30) {
      throw const CryptoFailure('public key is not DER (expected a SEQUENCE tag)');
    }
    final outer = ASN1Parser(der).nextObject();
    if (outer is! ASN1Sequence || outer.elements.length < 2) {
      throw const CryptoFailure('malformed SPKI: outer SEQUENCE expected');
    }
    // SPKI ::= SEQUENCE { algorithm AlgorithmIdentifier, subjectPublicKey BIT STRING }
    final bitString = outer.elements[1];
    if (bitString is! ASN1BitString) {
      throw const CryptoFailure('malformed SPKI: BIT STRING expected');
    }
    final inner = ASN1Parser(Uint8List.fromList(bitString.stringValue)).nextObject();
    if (inner is! ASN1Sequence || inner.elements.length < 2) {
      throw const CryptoFailure('malformed RSAPublicKey SEQUENCE');
    }
    final modulus = inner.elements[0];
    final exponent = inner.elements[1];
    if (modulus is! ASN1Integer || exponent is! ASN1Integer) {
      throw const CryptoFailure('malformed RSAPublicKey INTEGERs');
    }
    return RSAPublicKey(modulus.valueAsBigInteger, exponent.valueAsBigInteger);
  }

  /// RSA-OAEP encoder with SHA-256 for both the digest and MGF1, and no label.
  ///
  /// This must match pycryptodome's `PKCS1_OAEP.new(key, hashAlgo=SHA256)`, whose
  /// MGF defaults to MGF1 seeded with the same hash. pointycastle's default MGF
  /// is SHA-1, which produces a payload the server cannot decrypt.
  static OAEPEncoding _oaepEncoder(RSAPublicKey key) {
    final encoder = OAEPEncoding.withCustomDigest(
      () => SHA256Digest(),
      RSAEngine(),
    );
    encoder.init(true, PublicKeyParameter<RSAPublicKey>(key));
    return encoder;
  }

  /// Wrap [rawAesKey] for the server, returning standard base64.
  static String wrapAesKey(RSAPublicKey publicKey, Uint8List rawAesKey) {
    final wrapped = _oaepEncoder(publicKey).process(rawAesKey);
    return b64Encode(wrapped);
  }

  // ------------------------------------------------------------------ //
  // AES-GCM
  // ------------------------------------------------------------------ //
  GCMBlockCipher _gcm(Uint8List key, Uint8List iv, {required bool forEncryption}) {
    final cipher = GCMBlockCipher(AESEngine());
    cipher.init(
      forEncryption,
      // macSize is in bits. No associated data: the server passes none.
      AEADParameters(KeyParameter(key), kTagLength * 8, iv, Uint8List(0)),
    );
    return cipher;
  }

  /// Encrypt [plaintext] under [key] with a fresh random IV.
  ///
  /// `GCMBlockCipher.process` returns `ciphertext || tag`, which is already the
  /// layout the server expects, so the result is base64-encoded as-is.
  EncryptedEnvelope aesEncrypt(Uint8List key, List<int> plaintext) {
    _assertKeyLength(key);
    final iv = randomBytes(kIvLength);
    final out = _gcm(key, iv, forEncryption: true)
        .process(Uint8List.fromList(plaintext));
    return EncryptedEnvelope(iv: b64Encode(iv), ciphertext: b64Encode(out));
  }

  /// Decrypt an envelope, verifying the appended tag.
  ///
  /// Throws [CryptoFailure] when the payload has been tampered with, which is
  /// what callers surface as a transport error rather than a parse error.
  Uint8List aesDecrypt(Uint8List key, EncryptedEnvelope envelope) {
    _assertKeyLength(key);
    final Uint8List iv;
    final Uint8List blob;
    try {
      iv = b64Decode(envelope.iv);
      blob = b64Decode(envelope.ciphertext);
    } on FormatException catch (e) {
      throw CryptoFailure('envelope is not valid base64: ${e.message}');
    }
    if (iv.length != kIvLength) {
      throw CryptoFailure('iv must be $kIvLength bytes, got ${iv.length}');
    }
    if (blob.length < kTagLength) {
      throw const CryptoFailure('ciphertext shorter than the auth tag');
    }
    try {
      return _gcm(key, iv, forEncryption: false).process(blob);
    } catch (e) {
      // InvalidCipherTextException means the tag did not verify.
      throw CryptoFailure('could not authenticate payload: $e');
    }
  }

  /// Encrypt a JSON-encodable value, returning the envelope.
  EncryptedEnvelope encryptJson(Uint8List key, Object? value) =>
      aesEncrypt(key, utf8.encode(jsonEncode(value)));

  /// Decrypt an envelope and parse it as JSON.
  Object? decryptJson(Uint8List key, EncryptedEnvelope envelope) {
    final plain = utf8.decode(aesDecrypt(key, envelope));
    if (plain.isEmpty) return null;
    try {
      return jsonDecode(plain);
    } on FormatException {
      // The server always sends JSON here, but returning the raw text is more
      // useful than throwing if that ever changes.
      return plain;
    }
  }

  static void _assertKeyLength(Uint8List key) {
    if (key.length != 16 && key.length != 24 && key.length != 32) {
      throw CryptoFailure('AES key must be 16, 24 or 32 bytes, got ${key.length}');
    }
  }
}
